// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnUEXvzFEMjcAuMCC46cQKmDdYrtIzoT0',
    appId: '1:999888332644:web:aadbf00cf2cc5b5a78bc71',
    messagingSenderId: '999888332644',
    projectId: 'schoolfacilitiesbookingsystem',
    authDomain: 'schoolfacilitiesbookingsystem.firebaseapp.com',
    storageBucket: 'schoolfacilitiesbookingsystem.firebasestorage.app',
    measurementId: 'G-ZGH4V455HP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGXcrxERt-JIrYNYdSC5nNPjtDctC5vE4',
    appId: '1:999888332644:ios:eff96bfc45b145ea78bc71',
    messagingSenderId: '999888332644',
    projectId: 'schoolfacilitiesbookingsystem',
    storageBucket: 'schoolfacilitiesbookingsystem.firebasestorage.app',
    iosBundleId: 'com.example.smartSchoolFacilitiesBookingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnUEXvzFEMjcAuMCC46cQKmDdYrtIzoT0',
    appId: '1:999888332644:web:cd4aaacdd364f93a78bc71',
    messagingSenderId: '999888332644',
    projectId: 'schoolfacilitiesbookingsystem',
    authDomain: 'schoolfacilitiesbookingsystem.firebaseapp.com',
    storageBucket: 'schoolfacilitiesbookingsystem.firebasestorage.app',
    measurementId: 'G-HSND2CK113',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVL2d4D5aq5jYXmLTFMny70Q0N99_qstA',
    appId: '1:999888332644:android:c217965cffadb03778bc71',
    messagingSenderId: '999888332644',
    projectId: 'schoolfacilitiesbookingsystem',
    storageBucket: 'schoolfacilitiesbookingsystem.firebasestorage.app',
  );

}