import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:smart_school_facilities_booking_system/web/web_booking_list.dart';
import 'package:smart_school_facilities_booking_system/web/web_categories.dart';
import 'firebase_options.dart'; // ✅ generated by `flutterfire configure`
import 'package:go_router/go_router.dart';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import 'mobile/android_login.dart';
import 'mobile/android_list_of_facilities.dart';

import 'web/web_login.dart';
import 'web/manager_web_homepage.dart';
import 'web/web_account.dart';
import 'web/web_facilities.dart';
import 'web/web_list_manager.dart';
import 'package:smart_school_facilities_booking_system/web/admin_web_homepage.dart';
import 'web/web_booking_list.dart';

class UserRoleCache {
  static String? role;
}

class GoRouterRefreshStream extends ChangeNotifier {
  GoRouterRefreshStream(Stream<dynamic> stream) {
    notifyListeners();
    _subscription = stream.asBroadcastStream().listen((_) => notifyListeners());
  }
  late final StreamSubscription<dynamic> _subscription;

  @override
  void dispose() {
    _subscription.cancel();
    super.dispose();
  }
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ One line for every platform (Android/Web/iOS/Windows)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Optional but nice on Web: keep auth after refresh/close
  if (kIsWeb) {
    await FirebaseAuth.instance.setPersistence(Persistence.LOCAL);
  }

  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late final GoRouter _router;
  late final VoidCallback _routeListener;

  @override
  void initState() {
    super.initState();

    _router = GoRouter(
      refreshListenable: GoRouterRefreshStream(FirebaseAuth.instance.authStateChanges()),
      redirect: (context, state) {
        final user = FirebaseAuth.instance.currentUser;
        final isLoggingIn = state.uri.path == '/login';

        if (user == null) {
          return isLoggingIn ? null : '/login';
        } else {
          if (isLoggingIn) {
            final role = UserRoleCache.role ?? '';
            if (role == 'Admin') return '/admin';
            if (role == 'Manager') return '/manager';
            return '/login';
          }
          return null;
        }
      },
      routes: [
        GoRoute(
          path: '/login',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: WebLoginPage(),
          ),
        ),
        GoRoute(
          path: '/admin',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: AdminWebHomepage(),
          ),
        ),
        GoRoute(
          path: '/manager',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: ManagerWebHomepage(),
          ),
        ),
        GoRoute(
          path: '/webaccount',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: WebAccount(),
          ),
        ),
        GoRoute(
          path: '/facilitiespage',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: WebFacilities(),
          ),
        ),
        GoRoute(
          path: '/listmanagerpage',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: WebListManager(),
          ),
        ),
        GoRoute(
          path: '/categoriespage',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child:CategoriesPage(),
          ),
        ),
        GoRoute(
          path: '/bookinglist',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child:BookingList(),
          ),
        ),
      ],
    );

    // Properly add & remove the same listener
    _routeListener = () {
      final location = _router.routerDelegate.currentConfiguration.uri.path;
      final user = FirebaseAuth.instance.currentUser;

      if (user != null && location == '/login') {
        WidgetsBinding.instance.addPostFrameCallback((_) {
          if (!mounted) return;
          _router.go(UserRoleCache.role == 'Admin' ? '/admin' : '/manager');
        });
      }
    };
    _router.routerDelegate.addListener(_routeListener);
  }

  @override
  void dispose() {
    _router.routerDelegate.removeListener(_routeListener);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: kIsWeb ? const Size(1920, 1080) : const Size(412, 915),
      minTextAdapt: true,
      splitScreenMode: true,
      builder: (context, child) {
        if (kIsWeb) {
          // Web uses GoRouter
          return MaterialApp.router(
            debugShowCheckedModeBanner: false,
            title: 'SMART School Facility Booking System',
            theme: ThemeData(
              fontFamily: 'Poppins',
              textTheme: TextTheme(
                bodyLarge: TextStyle(fontSize: 20.sp),
                bodyMedium: TextStyle(fontSize: 15.sp),
                titleLarge: TextStyle(fontSize: 23.sp, fontWeight: FontWeight.bold),
              ),
            ),
            routerConfig: _router,
          );
        } else {
          // Mobile uses normal MaterialApp
          return MaterialApp(
            debugShowCheckedModeBanner: false,
            title: 'SMART School Facility Booking System',
            theme: ThemeData(
              scaffoldBackgroundColor: Colors.white,
              fontFamily: 'Poppins',
              textTheme: TextTheme(
                bodyLarge: TextStyle(fontSize: 20.sp),
                bodyMedium: TextStyle(fontSize: 15.sp),
                titleLarge: TextStyle(fontSize: 23.sp, fontWeight: FontWeight.bold),
              ),
            ),
            home: AndroidLoginPage(),
          );
        }
      },
    );
  }
}
