import 'dart:async';                                     // async tools

import 'package:flutter/foundation.dart';                // kIsWeb, debug flags
import 'package:flutter/material.dart';                  // Flutter UI

import 'package:firebase_core/firebase_core.dart';       // Firebase core
import 'package:firebase_auth/firebase_auth.dart';       // Auth
import 'package:cloud_firestore/cloud_firestore.dart';   // Firestore

import 'package:flutter_screenutil/flutter_screenutil.dart'; // responsive sizes
import 'package:go_router/go_router.dart';               // router
import 'package:smart_school_facilities_booking_system/web/web_view_rating.dart';

import 'firebase_options.dart';                          // generated by flutterfire

// ---- Mobile pages (home for mobile) ----
import 'mobile/android_login.dart';
import 'mobile/android_list_of_facilities.dart';
// ---- Web pages (used by router) ----
import 'web/web_login.dart';
import 'web/web_account.dart';
import 'web/web_facilities.dart';
import 'web/web_list_manager.dart';
import 'package:smart_school_facilities_booking_system/web/web_homepage.dart';
import 'web/web_booking_list.dart';
import 'web/web_booking.dart';
import 'web/web_notification.dart';
import 'web/web_categories.dart';
import 'web/web_statistic.dart';
import 'web/web_view_rating.dart';
import 'web/web_faq.dart';
import 'web/web_tnc.dart';
import 'web/web_lecturer_list.dart';
// ---- Local notification helper you already have ----
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'local_notify.dart';


// -----------------------------
// Simple cache for user role
// -----------------------------
class UserRoleCache {
  static String? role;                                   // store role string
}

// -------------------------------------------------------
// A small wrapper to let GoRouter refresh on auth changes
// -------------------------------------------------------
class GoRouterRefreshStream extends ChangeNotifier {
  // constructor: listen to any stream and call notify when it emits
  GoRouterRefreshStream(Stream<dynamic> stream) {
    notifyListeners();                                    // tell listeners once now
    _subscription = stream
        .asBroadcastStream()
        .listen((_) => notifyListeners());                // notify when stream emits
  }

  late final StreamSubscription<dynamic> _subscription;   // remember sub to cancel

  @override
  void dispose() {
    _subscription.cancel();                               // stop listening
    super.dispose();
  }
}

// -------------------------------------------------------
// Local notifications plugin (single instance)
// -------------------------------------------------------
final FlutterLocalNotificationsPlugin localNotifications =
FlutterLocalNotificationsPlugin();

// -------------------------------------------------------
// Initialize local notification channels (Android)
// We keep 2 channels:
//  - inbox_updates: your normal inbox events (approval, created, etc.)
//  - booking_reminders: used by FCM reminder popups (foreground) + default for background
// -------------------------------------------------------
Future<void> initLocalNotifications() async {
  // step 1: Android specific init (uses your mipmap launcher icon)
  const AndroidInitializationSettings androidInit =
  AndroidInitializationSettings('@mipmap/ic_launcher');

  // step 2: generic init settings (Android only for now)
  const InitializationSettings initSettings =
  InitializationSettings(android: androidInit);

  // step 3: initialize the plugin
  await localNotifications.initialize(initSettings);

  // step 4: create "inbox_updates" channel (high importance)
  const AndroidNotificationChannel inboxChannel = AndroidNotificationChannel(
    'inbox_updates',                                     // channel id
    'Inbox Updates',                                     // channel name
    description: 'Booking & approval alerts',            // channel description
    importance: Importance.max,                          // heads-up on Android 12+
  );

  // step 5: create "booking_reminders" channel (high importance)
  const AndroidNotificationChannel remindersChannel = AndroidNotificationChannel(
    'booking_reminders',                                 // MUST match Manifest meta-data
    'Booking Reminders',                                 // channel name
    description: 'Time-based reminders from FCM',        // channel description
    importance: Importance.high,                         // high is enough here
  );

  // step 6: resolve Android implementation to create channels
  final androidImpl = localNotifications
      .resolvePlatformSpecificImplementation<
      AndroidFlutterLocalNotificationsPlugin>();

  // step 7: actually create both channels
  await androidImpl?.createNotificationChannel(inboxChannel);
  await androidImpl?.createNotificationChannel(remindersChannel);

  // step 8: Android 13+ runtime permission (no-op on older)
  await androidImpl?.requestNotificationsPermission();
}

// -------------------------------------------------------
// MAIN entry
// -------------------------------------------------------
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

// MOBILE: init your local notification plugin/channels
  if (!kIsWeb) {
    await LocalNotify.init();
    await initLocalNotifications();
  }


  if (kIsWeb) {
    await FirebaseAuth.instance.setPersistence(Persistence.LOCAL);
  }

  runApp(const MyApp());
}


// -------------------------------------------------------
// Root widget (Stateful so we can hold router + listeners)
// -------------------------------------------------------
class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

// -------------------------------------------------------
// App state: sets up router + auth/inbox listeners
// -------------------------------------------------------
class _MyAppState extends State<MyApp> with WidgetsBindingObserver {

  late final GoRouter _router;                           // router instance
  late final VoidCallback _routeListener;                // router listener

  // subscriptions we need to clean up later
  StreamSubscription<User?>? _authSub;                   // auth state stream sub
  StreamSubscription<QuerySnapshot<Map<String, dynamic>>>? _inboxSub;   // inbox stream sub
  StreamSubscription<DocumentSnapshot<Map<String, dynamic>>>? _settingsSub; // settings sub

  // notification toggles (read from user doc)
  bool _notifAll = true;
  bool _notifApprovalBook = true;
  bool _notifNewBook = true;
  bool _notifReminder = true;
  bool _notifUpdatedBook = true;

  Timer? _minuteTicker;
  AppLifecycleState _lifeState = AppLifecycleState.resumed;
  // --- Build a local DateTime from "YYYY-MM-DD" + either slotKey "HHmm" or start "HH:MM"
  DateTime? _toLocalDateTime(String dateYMD, {String? slotKey, String? startHHmm}) {
    try {
      final p = dateYMD.split('-');                 // split date parts
      if (p.length != 3) return null;
      final int y = int.parse(p[0]);
      final int m = int.parse(p[1]);
      final int d = int.parse(p[2]);

      String t = '';
      if (startHHmm != null && startHHmm.trim().isNotEmpty) {
        t = startHHmm.trim();                       // use "HH:MM" if given
      } else if (slotKey != null && slotKey.trim().isNotEmpty) {
        String k = slotKey.trim().replaceAll(':', '');  // use "HHmm"
        if (k.length < 4) k = k.padLeft(4, '0');
        t = k.substring(0, 2) + ':' + k.substring(2, 4); // -> "HH:MM"
      } else {
        return null;
      }

      final tp = t.split(':');                      // parse time
      if (tp.length != 2) return null;
      final int hh = int.parse(tp[0]);
      final int mm = int.parse(tp[1]);

      return DateTime(y, m, d, hh, mm);            // local device time
    } catch (_) {
      return null;                                  // invalid -> null
    }
  }
  int _pickOneThreshold(Duration leftAtApproval) {
    final h = leftAtApproval.inHours;
    if (h >= 24) return 24;
    if (h >= 12) return 12;
    if (h >= 6)  return 6;
    if (h >= 1)  return 1;
    return 0; // too close -> no reminder
  }



  Future<void> _resyncUpcomingReminders(String uid) async {
    if (kIsWeb) return;

    const freshWindow = Duration(minutes: 5); // how long the trigger stays valid

    final qs = await FirebaseFirestore.instance
        .collection('Bookings')
        .where('userId', isEqualTo: uid)
        .where('approval', whereIn: ['accepted', 'approved'])
        .where('status', isEqualTo: 'upcoming')
        .get();

    for (final doc in qs.docs) {
      final m = doc.data();

      // Skip cancelled/deleted
      if ((m['deleted'] == true) ||
          ((m['status'] ?? '').toString().toLowerCase() == 'cancelled')) {
        await doc.reference.set({'reminderSent': {'any': true}}, SetOptions(merge: true));
        continue;
      }

      // Build start time from your fields
      final String date    = (m['bookingDate'] ?? '').toString().trim();
      final String slotKey = (m['slotKey'] ?? '').toString().trim();
      final String startStr= (m['start'] ?? '').toString().trim();
      final DateTime? startAt = _toLocalDateTime(
        date,
        slotKey: slotKey.isNotEmpty ? slotKey : null,
        startHHmm: startStr.isNotEmpty ? startStr : null,
      );
      if (startAt == null) continue;

      // Baseline time (when it was approved/created)
      DateTime? approvedAt;
      final a = m['approvedAt'];
      if (a is Timestamp) approvedAt = a.toDate();
      approvedAt ??= (m['createdAt'] is Timestamp)
          ? (m['createdAt'] as Timestamp).toDate()
          : null;
      if (approvedAt == null) continue;

      // --- RE-ARM + PLAN + FIRE ---

      // Read previous plan/flag
      Map<String, dynamic> sent =
          (m['reminderSent'] as Map?)?.cast<String, dynamic>() ?? {};
      final Map<String, dynamic> oldPlan =
          (sent['plan'] as Map?)?.cast<String, dynamic>() ?? {};

      DateTime? plannedStartAt;
      final plannedStartRaw = oldPlan['startAt'];
      if (plannedStartRaw is Timestamp) plannedStartAt = plannedStartRaw.toDate();

      // If reminder was done BUT start time changed -> clear to re-arm
      final bool timeChanged =
          plannedStartAt == null || (plannedStartAt.difference(startAt).inMinutes).abs() >= 1;
      if ((sent['any'] as bool? ?? false) && timeChanged) {
        await doc.reference.set({'reminderSent': {}}, SetOptions(merge: true));
        sent = {}; // re-armed
      }

      // If still marked done and time didn't change, skip
      if ((sent['any'] as bool?) == true) continue;

      // Choose threshold after possible re-arm
      final now = DateTime.now();
      final Duration basis = sent.isEmpty
          ? startAt.difference(now)                 // re-armed or first plan
          : startAt.difference(approvedAt);         // existing plan baseline

      final int chosenH = _pickOneThreshold(basis);
      if (chosenH == 0) {
        // too close -> no reminder
        final out0 = Map<String, dynamic>.from(sent);
        out0['any'] = true;
        await doc.reference.set({'reminderSent': out0}, SetOptions(merge: true));
        continue;
      }

      final DateTime trigger = startAt.subtract(Duration(hours: chosenH));

      // Save plan and decide: missed / wait / fire
      final Map<String, dynamic> out = Map<String, dynamic>.from(sent);
      out['plan'] = {
        'h': chosenH,
        'triggerAt': Timestamp.fromDate(trigger),
        'startAt': Timestamp.fromDate(startAt),
      };

      if (now.isAfter(trigger.add(freshWindow))) {
        // Missed -> mark done, no late reminder
        out['any'] = true;
        await doc.reference.set({'reminderSent': out}, SetOptions(merge: true));
        continue;
      }

      if (now.isBefore(trigger)) {
        // Not yet time -> store plan only
        await doc.reference.set({'reminderSent': out}, SetOptions(merge: true));
        continue;
      }

      // Within window -> show once and mark done
      if (_notifAll && _notifReminder) {
        final fac = (m['facilityName'] ?? m['facility'] ?? 'Booking').toString();
        LocalNotify.show(
          id: (doc.id + '_rem').hashCode & 0x7fffffff,
          title: 'Booking reminder',
          body: '$fac • ${chosenH}h before start',
        );
      }
      out['any'] = true;
      await doc.reference.set({'reminderSent': out}, SetOptions(merge: true));
    }
  }




  // -----------------------------------------
  // read or create "inboxLastSeen" on user doc
  // -----------------------------------------
  Future<Timestamp> _readOrInitLastSeenFS(String uid) async {
    final docRef = FirebaseFirestore.instance
        .collection('UserInformation')
        .doc(uid);                                       // point to user doc

    final snap = await docRef.get();                     // read once

    if (snap.exists == true) {                           // if doc exists
      final data = snap.data();                          // get map
      if (data != null &&
          data.containsKey('inboxLastSeen') &&
          data['inboxLastSeen'] is Timestamp) {
        return data['inboxLastSeen'] as Timestamp;       // return stored ts
      }
    }

    final now = Timestamp.now();                         // first time -> now
    await docRef.set({'inboxLastSeen': now}, SetOptions(merge: true));
    return now;                                          // return the saved ts
  }

  // -----------------------------------------
  // write newest lastSeen after processing
  // -----------------------------------------
  Future<void> _writeLastSeenFS(String uid, Timestamp ts) async {
    final docRef = FirebaseFirestore.instance
        .collection('UserInformation')
        .doc(uid);                                       // point to user doc
    await docRef.set({'inboxLastSeen': ts}, SetOptions(merge: true));
  }

  // -------------------------------------------------------
  // Start inbox listener (only docs newer than lastSeen)
  // -------------------------------------------------------
  Future<void> _startInboxListenerFS(User user) async {
    _inboxSub?.cancel();                                 // avoid duplicate subs

    final Timestamp lastSeenAtStart =
    await _readOrInitLastSeenFS(user.uid);           // get baseline ts

    final Query<Map<String, dynamic>> q = FirebaseFirestore.instance
        .collection('UserInformation')
        .doc(user.uid)
        .collection('Inbox')
        .where('createdAt', isGreaterThan: lastSeenAtStart)
        .orderBy('createdAt');                           // sort by time

    _inboxSub = q.snapshots().listen((qs) async {
      Timestamp newest = lastSeenAtStart;                // track newest ts

      for (final c in qs.docChanges) {
        if (c.type != DocumentChangeType.added) {        // only new docs
          continue;
        }

        final m = c.doc.data();                          // get map
        if (m == null) { continue; }

        if (m['isRead'] == true) {                       // already read -> skip popup
          continue;
        }

        if (_notifAll == false) {                        // master off -> skip all
          continue;
        }

        // safe read createdAt
        Timestamp createdAt = Timestamp.now();           // fallback now
        final any = m['createdAt'];
        if (any is Timestamp) {
          createdAt = any;
        }

        // simple fields
        final String type = (m['type'] ?? '').toString();
        final String facility =
        (m['facilityName'] ?? m['facility'] ?? 'SMART booking').toString();
        final String approval =
        (m['approval'] ?? m['approvalStatus'] ?? '').toString().toLowerCase();

        // build title/body with basic if/else only
        String title;
        String body = facility;

        if (type == 'booking_created') {
          if (_notifNewBook == false) { continue; }
          if (approval == 'pending') { continue; }
          title = 'Booked successfully';
        } else if (type == 'booking_updated') {
          if (_notifUpdatedBook == false) { continue; }
          title = 'Booking updated';
        } else if (type == 'approval_status') {
          if (_notifApprovalBook == false) { continue; }
          if (approval.contains('accept') || approval.contains('approv')) {
            title = 'Facility approved';
          } else if (approval.contains('reject') ||
              approval.contains('declin') ||
              approval.contains('deni')) {
            title = 'Facility rejected';
          } else {
            title = 'Booking updated';
          }
        } else if (type == 'reminder') {
          // FYI: real reminders now come via FCM.
          // We still allow Inbox "reminder" entries for history if you create them,
          // but you can skip showing a popup here if you want.
          if (_notifReminder == false) { continue; }
          title = 'Booking reminder';
        } else if (type == 'request_update') {
          title = 'Action needed';
          final String date = (m['bookingDate'] ?? '').toString().trim();
          final String facName = (m['facilityName'] ?? '').toString().trim();
          if (facName.isNotEmpty && date.isNotEmpty) {
            body = '$facName • $date — please change booking date';
          } else if (date.isNotEmpty) {
            body = 'Please change your booking date: $date';
          } else {
            body = 'Please change your booking date';
          }
        } else if (type == 'booking_deleted') {
          if (_notifReminder == false) { continue; }
          title = 'Your booking have been deleted';
        } else {
          title = 'Notification';
          final String msg = (m['message'] ?? '').toString().trim();
          if (msg.isNotEmpty) { body = msg; }
        }

        // show a local heads-up (mobile only)
        if (!kIsWeb) {
          LocalNotify.show(
            id: c.doc.id.hashCode & 0x7fffffff,          // stable int id
            title: title,
            body: body,
          );
        }

        // remember newest time we saw
        if (createdAt.compareTo(newest) > 0) {
          newest = createdAt;
        }
      }

      // bump lastSeen after processing
      if (newest.compareTo(lastSeenAtStart) > 0) {
        await _writeLastSeenFS(user.uid, newest);
      }
    });
  }

  // -------------------------------------------------------
  // initState: build router + attach listeners
  // -------------------------------------------------------
  @override
  void initState() {

    super.initState();

    // build router (same logic you had)
    _router = GoRouter(
      refreshListenable:
      GoRouterRefreshStream(FirebaseAuth.instance.authStateChanges()),
      redirect: (context, state) {
        final user = FirebaseAuth.instance.currentUser;   // current user
        final isLoggingIn = state.uri.path == '/login';   // are we on /login ?

        if (user == null) {                               // not signed in
          return isLoggingIn ? null : '/login';           // force to /login
        } else {
          if (isLoggingIn) {                              // already logged in
            final role = UserRoleCache.role ?? '';
            if (role == 'Admin') return '/homepage';
            if (role == 'Manager') return '/homepage';
            return '/login';
          }
          return null;                                    // stay where you are
        }
      },
      routes: [
        GoRoute(
          path: '/login',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: WebLoginPage(),
          ),
        ),
        GoRoute(
          path: '/homepage',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: Homepage(),
          ),
        ),
        GoRoute(
          path: '/webaccount',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: WebAccount(),
          ),
        ),
        GoRoute(
          path: '/facilitiespage',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: WebFacilities(),
          ),
        ),
        GoRoute(
          path: '/listmanagerpage',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: WebListManager(),
          ),
        ),
        GoRoute(
          path: '/categoriespage',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: CategoriesPage(),
          ),
        ),
        GoRoute(
          path: '/bookinglist',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: BookingList(),
          ),
        ),
        GoRoute(
          path: '/webbooking',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: WebBooking(),
          ),
        ),
        GoRoute(
          path: '/webnotification',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: WebNotification(),
          ),
        ),
        GoRoute(
          path: '/webstatistic',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: WebStatistic(),
          ),
        ),
        GoRoute(
          path: '/webviewrating',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: WebViewRating(),
          ),
        ),
        GoRoute(
          path: '/webfaq',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: WebFAQ(),
          ),
        ),
        GoRoute(
          path: '/webtnc',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: WebTNC(),
          ),
        ),
        GoRoute(
          path: '/lecturerlist',
          pageBuilder: (context, state) => MaterialPage<void>(
            key: state.pageKey,
            child: LecturerList(),
          ),
        ),
      ],
    );

    // watch router location to auto-redirect after login
    _routeListener = () {
      final location = _router.routerDelegate.currentConfiguration.uri.path;
      final user = FirebaseAuth.instance.currentUser;

      if (user != null && location == '/login') {
        WidgetsBinding.instance.addPostFrameCallback((_) {
          if (!mounted) return;
          _router.go(UserRoleCache.role == 'Admin' ? '/admin' : '/manager');
        });
      }
    };
    _router.routerDelegate.addListener(_routeListener);
    WidgetsBinding.instance.addObserver(this);
    // keep current lifecycle guess
    _lifeState = AppLifecycleState.resumed;

// tick every minute while app is in foreground
    _minuteTicker = Timer.periodic(const Duration(minutes: 1), (_) async {
      final u = FirebaseAuth.instance.currentUser;
      if (u != null && _lifeState == AppLifecycleState.resumed) {
        await _resyncUpcomingReminders(u.uid);
      }
    });

    // MOBILE: set up auth + inbox listeners and attach FCM token to user
    if (!kIsWeb) {
      _authSub = FirebaseAuth.instance.authStateChanges().listen((user) async {
        // stop old streams
        _inboxSub?.cancel();
        _settingsSub?.cancel();

        if (user == null) {
          // stop reminder ticker when signed out

          return;
        }

        // run one scan immediately on sign-in
        await _resyncUpcomingReminders(user.uid);

        // start ticking every minute while foreground


        // listen to user notification settings
        _settingsSub = FirebaseFirestore.instance
            .collection('UserInformation')
            .doc(user.uid)
            .snapshots()
            .listen((doc) {
          if (!doc.exists) return;
          final data = doc.data() ?? {};
          _notifAll = data['notifAll'] ?? true;
          _notifApprovalBook = data['notifApprovalBook'] ?? true;
          _notifNewBook = data['notifNewBook'] ?? true;
          _notifReminder = data['notifReminder'] ?? true;
          _notifUpdatedBook = data['notifUpdatedBook'] ?? true;
        });

        // listen to Inbox for new items (pop local heads-up)
        await _startInboxListenerFS(user);
      });

    }

    // IMPORTANT CHANGE:
    // We REMOVED all local rescheduling of reminders:
    //  - No _toLocalDateTime()
    //  - No _resyncUpcomingReminders()
    //  - No ReminderService().rescheduleBookingReminder(...)
    // Reminders now come via FCM from your Cloud Function.
  }
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    _lifeState = state;
    if (state == AppLifecycleState.resumed) {
      final u = FirebaseAuth.instance.currentUser;
      if (u != null) {
        _resyncUpcomingReminders(u.uid); // immediate check when app comes to foreground
      }
    }
  }



  // -------------------------------------------------------
  // dispose: clean up listeners
  // -------------------------------------------------------
  @override
  void dispose() {
    _router.routerDelegate.removeListener(_routeListener); // remove router listener
    _inboxSub?.cancel();                                   // stop inbox stream
    _authSub?.cancel();                                    // stop auth stream
    _settingsSub?.cancel();                                // stop settings stream
    WidgetsBinding.instance.removeObserver(this);
    _minuteTicker?.cancel();

    super.dispose();
  }

  // -------------------------------------------------------
  // build: keeps your ScreenUtilInit + web/router vs mobile/home
  // -------------------------------------------------------
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: kIsWeb ? const Size(1920, 1080) : const Size(412, 915),
      minTextAdapt: true,
      splitScreenMode: true,
      builder: (context, _) {
        // Build one theme used by both web & mobile
        final ThemeData appTheme = ThemeData(
          scaffoldBackgroundColor: Colors.white,
          fontFamily: 'Poppins', // <-- uses your bundled font family name
          // If you want to use google_fonts instead:
          // textTheme: GoogleFonts.poppinsTextTheme(),
          textTheme: TextTheme(
            bodyLarge: TextStyle(fontSize: 20.sp),
            bodyMedium: TextStyle(fontSize: 15.sp),
            titleLarge: TextStyle(fontSize: 23.sp, fontWeight: FontWeight.bold),
          ),
        );

        if (kIsWeb) {
          // Keep your existing GoRouter on web
          return MaterialApp.router(
            debugShowCheckedModeBanner: false,
            title: 'SMART School Facility Booking System',
            theme: appTheme,
            routerConfig: _router, // your existing router instance
          );
        }

        // Mobile: super simple login vs facilities
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          title: 'SMART School Facility Booking System',
          theme: appTheme,
          home: const AuthGate(),
        );
      },
    );
  }
}

class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snap) {
        if (snap.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
        final user = snap.data ?? FirebaseAuth.instance.currentUser;
        return (user == null) ? AndroidLoginPage() : AndroidListOfFacilities();
      },
    );
  }
}

